### PR TITLE
Add support for PHP files

### PR DESCRIPTION
**Pull request by theofidry**
Closes #251.

### CODE REVIEW

**Comment by theofidry** [comment]
Thanks @enumag :)

**Comment by enumag** [comment]
@theofidry Nice, thanks! :-)

**Comment by appeltaert** [comment]
A new tag would be nice, since dev-master requires php7 ;)

**Comment by theofidry** [comment]
@appeltaert it's actually a mistake, `dev-master` should be `2.x-dev`, not `1.x-dev`. I'm planning to do a release soon, just waiting for some input from #202 and finish #257.

**Pull request merged**
