### PR TITLE
Fix lowest deps

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I don't understand this error: https://travis-ci.org/hautelook/AliceBundle/jobs/96001329#L232

Can't reproduce it on local.

**Comment by Soullivaneuh** [comment]
Oh, I can reproduce it after deleting the whole `vendor` folder.

But I still don't understand why. :-)

**Comment by theofidry** [comment]
er, can't really too actually. Is it coming from us or from composer?

**Comment by Soullivaneuh** [comment]
Don't know, but we haven't this error on `1.x`: https://travis-ci.org/hautelook/AliceBundle/jobs/96002182#L205

**Comment by Soullivaneuh** [comment]
I don't have the issue if I remove the `conflicts` key. Will open an issue.

**Comment by Soullivaneuh** [comment]
See https://github.com/composer/composer/issues/4687.

**Comment by theofidry** [comment]
No error to report anymore on this side so closing it.

**Comment by Soullivaneuh** [comment]
I don't think this PR should be closed. We have lower dependencies to fix anyway, like `doctrine/phpcr-odm`.

**Comment by theofidry** [comment]
Fair

**Pull request closed without merging**
