### PR TITLE
Support Symfony\Component\Finder\SplFileInfo when loading fixtures

### PR DESCRIPTION
**Pull request by teohhanhui**

### CODE REVIEW

**Comment by theofidry** [comment]
Can you tell me how you got this case? (just curious about it)

**Comment by teohhanhui** [comment]
I'll add a test case for this.

**Comment by teohhanhui** [comment]
Strangely, there's a failing test case on my machine:

```
PHPUnit 4.8.4 by Sebastian Bergmann and contributors.
Warning:	The Xdebug extension is not loaded
		No code coverage will be generated.

...............F....

Time: 1 second, Memory: 36.50Mb

There was 1 failure:

1) Hautelook\AliceBundle\Tests\Doctrine\Command\DoctrineFixtureTest::testFixturesRegistering with data set #7 (array('dev', array('TestCBundle')), '              > fixtures foun...oaded\n')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '> fixtures found:
+      - /home/vagrant/AliceBundle/Tests/SymfonyApp/TestBundle/Bundle/BBundle/DataFixtures/ORM/bentity.yml
       - /home/vagrant/AliceBundle/Tests/SymfonyApp/TestBundle/Bundle/ABundle/DataFixtures/ORM/aentity.yml
-      - /home/vagrant/AliceBundle/Tests/SymfonyApp/TestBundle/Bundle/BBundle/DataFixtures/ORM/bentity.yml
   > purging database
   > fixtures loaded
 '

/home/vagrant/AliceBundle/Tests/Doctrine/Command/DoctrineFixtureTest.php:81

FAILURES!
Tests: 20, Assertions: 63, Failures: 1.
```

(`master` branch)

**Comment by teohhanhui** [comment]
Seems like some assumptions were made that don't hold true all the time...

**Comment by theofidry** [comment]
Regarding the support for SplFileInfo: no problem there, but would be great to have tests for that. As there is not test for it yet, I can't ask you to do them for merging the PR, but if you can it would be great.

For your error, this comes from the fact that the fixtures may be loaded in different order from a machin to another, I should add a sort somewhere...

**Comment by teohhanhui** [comment]
I'm changing the type to `\SplFileInfo` to match what is actually supported by [doctrine/data-fixtures](https://github.com/doctrine/data-fixtures)

[Doctrine\Common\DataFixtures\Loader.php#L339](https://github.com/doctrine/data-fixtures/blob/81cd269006b37452389801e05974ba05bcd7005b/lib/Doctrine/Common/DataFixtures/Loader.php#L339)

**Comment by theofidry** [comment]
It's worth checking but it would be safer to get the fixture real path when having a `SplFileInfo` info IMO. My issue here is that it's a behaviour of the `Finder` component that I have not tested at all :/ I'll try to do that tonight so that I can merge your PR fast (unless you can do it before me^^)

**Pull request closed without merging**
