### PR TITLE
Allow doctrine/persistence 2.0

### PR DESCRIPTION
**Pull request by franmomu**
The necessary changes were made in https://github.com/hautelook/AliceBundle/pull/493.

Fixes https://github.com/hautelook/AliceBundle/issues/513, https://github.com/hautelook/AliceBundle/issues/514 and https://github.com/hautelook/AliceBundle/issues/519

~EDIT: It needs some more love 😬~

### CODE REVIEW

**Comment by froozeify** [comment]
Hey, I've just checked why the CI failed. 

It's apparently due to an alias that isn't supported anymore (doctrine/data-fixture made the change in late 2019, [Pull request #333](https://github.com/doctrine/data-fixtures/pull/333))

I found 3 reference to it in the project, I've fixed it locally and it seems all works on my project now.

They are in `README.md:385`, `Bridge/Doctrine/Persister/ObjectManagerPersister:17` and `Bridge/Doctrine/Purger/Purger:20`.
   
I've changed `use Doctrine\Common\Persistence\ObjectManager` to `use Doctrine\Persistence\ObjectManager;` and no problem seems to occured (php 7.4.5, symfony 4.4.13)

**Comment by franmomu** [comment]
Thanks for the help!

Those files belong to [`theofidry/alice-data-fixtures`](https://github.com/theofidry/AliceDataFixtures). There is an issue open [adding support for `doctrine/persistence` 2.0](https://github.com/theofidry/AliceDataFixtures/pull/148), but the tests were failing, now there are fixed in https://github.com/theofidry/AliceDataFixtures/pull/150, so we have to wait until that library supports `doctrine/persistence` 2.0.

**Comment by soyuka** [comment]
Hi! I tried your patch as I wanted to use php 5 and alice and it works to me. See https://github.com/soyuka/api-platform-alice-sf5/blob/master/composer.json for reproduction.

**Comment by franmomu** [comment]
Now the issue is that `theofidry/alice-data-fixtures` 1.3.0 which is compatible with `doctrine/persistence` 2.0 requires a minimum version of PHP 7.3 and tests are being executed in PHP 7.2.

@theofidry is it ok to bump this package to PHP 7.3? (if so, I'll make the PR)

**Comment by theofidry** [comment]
Yep 👍

**Comment by froozeify** [comment]
Hey, seems all test passed 👍  Any idea when it will be merged, and if a release tag will be made just after ?

**Comment by theofidry** [comment]
Thank you @franmomu

**Comment by Nyholm** [comment]
Thank you!

**Pull request merged**
