### PR TITLE
Update to Symfony LTS versions

### PR DESCRIPTION
**Pull request by theofidry**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Don't forget SF 3.1 on failures sections! :+1:

**Comment by theofidry** [comment]
We won't be able to support Symfony 3.0 with MongoDB :( doctrine/DoctrineMongoDBBundle#326

**Comment by Soullivaneuh** [comment]
We could maybe remove those dependencies and skip tests for PHP7, waiting for a compatibility.

For SF 3.0 compatibility, well, let's make some PRs?! :-D

**Comment by Soullivaneuh** [comment]
@theofidry https://github.com/doctrine/DoctrineMongoDBBundle/pull/327

**Comment by theofidry** [comment]
Closed in favour of #188

**Pull request closed without merging**
