### PR TITLE
travis: phpunit.xml.dist is used by default

### PR DESCRIPTION
**Pull request by TomasVotruba**
Also scrutinizer moved to after_script, since it's not part of testing procedure.

### CODE REVIEW

**Comment by baldurrensch** [comment]
Thank you!

**Comment by baldurrensch** [comment]
Scrutinizer build failed. I restarted

**Comment by TomasVotruba** [comment]
Sometimes scrutinizer gets buggy. Writing support just info message usually helps.

**Comment by TomasVotruba** [comment]
Any updates?

**Comment by theofidry** [comment]
@TomasVotruba can you rebase it?

**Comment by TomasVotruba** [comment]
It might take some time, so I'd recommend to it manually or in own commit.

**Pull request closed without merging**
