### PR TITLE
Allow PHP8

### LINKED ISSUE #525: Support for PHP8
Trying to do a composer install on PHP8 gives the error:

```
    - hautelook/alice-bundle is locked to version 2.8.0 and an update of this package was not requested.
    - hautelook/alice-bundle 2.8.0 requires php ^7.3 -> your php version (8.0.0) does not satisfy that requirement
```

I've tried the bundle with `--ignore-platform-reqs` and it doesn't seem to have issues

### PR DESCRIPTION
**Pull request by akira28**
fixes #525

### CODE REVIEW

**Comment by nicodmf** [comment]
@theofidry @dunglas any news on this, we begin a project with api platform & php8, could you merge this work ?

**Comment by theofidry** [comment]
This won't be enough as https://github.com/theofidry/AliceDataFixtures and https://github.com/nelmio/alice need to be updated as well however they are both blocked by https://github.com/wikimedia/composer-merge-plugin/pull/189

**Comment by nicodmf** [comment]
As, i can't wait to start the project i fork AliceBundle and AliceDataFixtures and this works, Alice not block the update process, and fixtures are loaded in my project

**Comment by akira28** [comment]
Let me know if I can help with something. Right now I'm installing with --ignore-platform-reqs but it's obviously not ideal :P

**Comment by alexislefebvre** [comment]
See https://github.com/theofidry/AliceDataFixtures/pull/158 for AliceDataFixtures

**Comment by nusphere** [comment]
any infos about this MR?

**Comment by VincentLanglet** [comment]
https://github.com/theofidry/AliceDataFixtures/pull/158 was needed,

now it can be updated by using `1.4.0`

**Comment by akira28** [comment]
I'm getting

```
1) Hautelook\AliceBundle\DependencyInjection\HautelookAliceBundleTest::testServiceRegistration

Symfony\Component\DependencyInjection\Exception\RuntimeException: Argument 1 of service "annotations.filesystem_cache" is abstract: Cache-Directory.
```

**Comment by VincentLanglet** [comment]
I got this error in https://github.com/theofidry/AliceDataFixtures/pull/160 @akira28 

I had to do something like https://github.com/theofidry/AliceDataFixtures/pull/160/files#diff-0b7ff62a4ba522a038c2d4facf8ebdb6164d42f80e96a996c252ff384f4b406aR22

But the config was loaded dynamically https://github.com/theofidry/AliceDataFixtures/pull/160/files#diff-db969fe1a146a486112d54eb683b0d88534b75cfa927b254511ec85bcb1bdccaR62 for SF3 vs SF4-5

**Comment by akira28** [comment]
sorry I don't have time to try it these days, if someone can help out I would be glad :)

**Comment by Dm3yZ** [comment]
Cache for annotations in files helps to pass tests, but I'm not sure if this is the legal way :)

fixtures/Functional/config/test/config.yml
```yaml
framework:
    secret: test
    test: ~
    annotation:
        cache: file
```

**Comment by jmsche** [comment]
> Cache for annotations in files helps to pass tests, but I'm not sure if this is the legal way :)
> 
> fixtures/Functional/config/test/config.yml
> 
> ```yaml
> framework:
>     secret: test
>     test: ~
>     annotation:
>         cache: file
> ```

I'd say "why not?" :)

I also think Symfony 3.4 should be dropped as it entered security fixes only phase.

**Comment by soyuka** [comment]
merged in https://github.com/hautelook/AliceBundle/pull/533 can be closed thanks @Dm3yZ @akira28

**Comment by theofidry** [comment]
Closed via #533, #534

**Pull request closed without merging**
