### PR TITLE
Disable foreign key checks before purge on MySqlPlatform

### PR DESCRIPTION
**Pull request by vincentchalamon**
From https://github.com/hautelook/AliceBundle/pull/197 & https://github.com/hautelook/AliceBundle/pull/198

### CODE REVIEW

**Comment by theofidry** [comment]
Maybe PHPUnit needs to be updated as well? (the Travis binary)

**Comment by vincentchalamon** [comment]
@theofidry I updated using vendor phpunit, and disable github-oauth-token, so there is no need to use `composer global require phpunit/phpunit`

**Comment by theofidry** [comment]
@vincentchalamon merged and released as 1.2.2. I deleted the 1.2.1 GitHub released although let the git tag.

**Comment by vincentchalamon** [comment]
Thanks @theofidry
Your 1.2.1 included your PR about PHP quotes. Don't forget to remerge it in a futur release ;)

**Comment by theofidry** [comment]
@vincentchalamon it is included, I just removed GitHub release :)

**Comment by vincentchalamon** [comment]
My bad, I haven't seen it. Great @theofidry :+1:

**Pull request merged**
