### PR TITLE
Remove unnecessary composer authentication

### PR DESCRIPTION
**Pull request by theofidry**
As [GitHub removed their hourly API rate limit](https://github.com/composer/composer/issues/4884#issuecomment-195229989), we can remove this now.

cc @Soullivaneuh

### CODE REVIEW

**Comment by vincentchalamon** [comment]
Your link is broken, can you update it?

**Comment by theofidry** [comment]
Done soz

**Comment by vincentchalamon** [comment]
What a good news :smiley:

**Comment by vincentchalamon** [comment]
:+1:

**Comment by Soullivaneuh** [comment]
Wow, that's great!

@theofidry Can you confirm it's working?

I should do the same on Sonata projects...

**Comment by theofidry** [comment]
@Soullivaneuh yep ;)

**Comment by theofidry** [comment]
Closed via #226

**Pull request closed without merging**
