### PR TITLE
Address deprecations from persistence lib

### PR DESCRIPTION
**Pull request by greg0ire**
A backwards-compatibility layer has been added to persistence to help
consumers move to the new namespacing. It is based on class aliases,
which means the type declaration changes should not be a BC-break: types
are the same.
See doctrine/persistence#71

This means:
- using the new namespaces
- adding autoload calls for new types to types that may be extended and
use persistence types in type declarations of non-constructor methods,
so that signature compatibility is recognized by old versions of php.
Luckily, none of those were found in this package.
More details on this at
https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf

### CODE REVIEW

**Comment by greg0ire** [comment]
I don't understand the Composer failure for the prefer-lowest build :thinking:

**Comment by greg0ire** [comment]
I understand now, I added it to `require` when there was already a requirement in the `require-dev` section. This looks wrong to me, by the way, since there are references to the persistence lib in `src`. Should I move it to the `require` section. Or is it there because it is considered a dependency only when using an optional feature? Since there is already a requirement for `doctrine/orm` this looks unlikely.

**Comment by theofidry** [comment]
No indeed, not sure why this one is in require-dev

**Comment by greg0ire** [comment]
Ok, let me move it.

**Comment by greg0ire** [comment]
@theofidry PTAL

**Comment by theofidry** [comment]
Thank you @greg0ire

**Pull request merged**
