### PR TITLE
Allow to pass parameters to Alice from configuration

### PR DESCRIPTION
**Pull request by sroze**
Related to the pull request made on Alice library (nelmio/alice#130), this pull request allow to add parameters directly from the bundle configuration.

If you look at the example wrote on the Alice's pull request, with this feature here, we simply have to set this configuration in `app/config/config.yml` and remove the `parameters` in fixtures files:
```yml
hautelook_alice:
    parameters:
        medias_path: %kernel.root_dir%/Resources/medias
```

### CODE REVIEW

**Comment by sroze** [comment]
@baldurrensch FYI that was merged a long time ago :smiley:

**Comment by sroze** [comment]
@theofidry ?! I was speaking about nelmio/alice#130 that is merged since a lot of time, so this one can be too.

**Comment by theofidry** [comment]
Erf, my bad. Could you debase te PR please?

**Comment by sroze** [comment]
I won't, too much changes, this one should have been merged before, as well as the small others btw.

**Comment by theofidry** [comment]
Yeah, maybe I should, but if possible I would like to avoid as much as possible the legacy work even though I certainly will have to do it at some point. I'll try to add this feature nonetheless, it's an interesting one.

**Pull request closed without merging**
