### PR TITLE
Bundle upgrade

### PR DESCRIPTION
**Pull request by theofidry**
Follow up of the discussion of #51.

The main changes are:
* support of custom processors
* support of custom providers
* upgrade of nelmio/alice to the 2.0 version
* relies on nelmio/alice loader instead of a custom one

Basically the bundle comes down to the `AbstractDataFixtureLoader` class and some services. There is still quite a few things I would like to enhance but well, that can be for later.

cc @hjr3

### CODE REVIEW

**Comment by estahn** [comment]
:+1:

**Comment by theofidry** [comment]
Thanks @estahn. I've tested my fork on some projects and works well with Doctrine ORM and the common use case.

Still, it would be great to have some feedback on it and also considering to add new features proposed by similar projects.

**Comment by umpirsky** [comment]
:+1:

**Comment by dunglas** [comment]
:+1: looks great!

**Comment by hjr3** [comment]
This is great work @theofidry ! Did you want to enhance the things you mentioned now or should we look at merging this in?

**Comment by theofidry** [comment]
Actually I wanted to discuss about that with you :)

This PR will imply a new release. Although the current release is 0.2 which is a dev one, it is more used like a 1.0.0. So we can either stick to the convention and merge this PR on the master and prevent the possibility to patch the 0.2, or create a 0.X branch.

Either way I think this PR could be released as a 1.0.0@beta rather than a 0.3. It's too early to release it as a 1.0.0 since not much people could use it yet.
For the functionalities I want to add, well I don't think they will cause any BC break we will be able to release them under the 1.X tag too.

IMO what's important now is to show that the bundle is still active and propose and upgraded version open too change and new features. The features I want to add can be added later.

Oh year, before any merging let's squash all this, but I wanted to wait for any review first :)

**Comment by theofidry** [comment]
And maybe more into the details, I find a bit heavy the naming for the services:
* tag for processors: `hautelook_alice.processor`
* tag for providers: `hautelook_alice.faker.provider`

Maybe they could be changed to `alice.processor` and `faker.provider`? (It's details really, but we want to avoid to introduce any BC break later let's take care of this now)

**Comment by estahn** [comment]
@theofidry In regards to renaming the services. Would this eventually collide with existing service names, e.g. an application thats called alice and uses an alice processor for some reason.

**Comment by theofidry** [comment]
ping @hjr3

**Comment by theofidry** [comment]
@hjr3 I rebased to clean it up. Tell me what you think about [this][https://github.com/hautelook/AliceBundle/pull/58#issuecomment-121374736).

**Comment by theofidry** [comment]
ping @hjr3

**Comment by sgb-io** [comment]
+1

**Comment by theofidry** [comment]
@hjr3 big changes: some refactoring and introduced a command to introduce new features and remove the dependency to DoctrineFixturesBundle. Doc updated too.

Ready to be launched under the `v1.0.0-beta` tag.

**Comment by hjr3** [comment]
@theofidry I made you a collaborator with write access. Go ahead and do the honors ;)

**Comment by theofidry** [comment]
@hjr3 thanks!!

**Comment by theofidry** [comment]
@hjr3 would it be possible to have access to the scrutinizer too?

**Comment by hjr3** [comment]
@theofidry i sync'ed the scrutinizer side, you should have access now

**Comment by theofidry** [comment]
I can schedule builds but I have no access to the settings and the configuration of the builds (that's the last one I'm the more interested in)

**Comment by hjr3** [comment]
It is not updating. I will try again in a bit.

**Comment by theofidry** [comment]
Got it

**Pull request merged**
