### PR TITLE
Remove deleted psr0 fixer for StyleCI

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Ref: https://blog.alt-three.com/psr4-fixer/

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Strange error from StyleCI. @theofidry could you take a look please?

**Comment by theofidry** [comment]
Well, not sure of what happened. Can you try to repush that and if it doesn't work I'm trying to repair it...

**Comment by Soullivaneuh** [comment]
@theofidry How? Can't rebase from master, it's up to date.

I think you can restart the job [here](https://styleci.io/analyses/Xk55Jz), isn't it?

**Comment by theofidry** [comment]
No I can't :(

You can do an empty commit and then remove it :/

**Comment by Soullivaneuh** [comment]
@theofidry Working. :+1: 

> No I can't :(

Hmm, this is bad. We should suggest it to StyleCI (ping @GrahamCampbell).

**Pull request merged**
