### PR TITLE
Fix doc

### LINKED ISSUE #129: Custom Provider : Circular Reference
Hello, i'm trying to create a custom faker provider but i'm stuck with a circular reference exception. 

Here is my configuration :

```json
// composer.json
// ...
    "doctrine/doctrine-fixtures-bundle": "^2.2",
    "hautelook/alice-bundle": "v1.0.0-beta.5"
// ...
```

```yaml
# config_dev.yml
hautelook_alice:
    db_drivers:
        orm: ~
    locale: fr_FR
    seed: 1
    persist_once: true
    loading_limit: 5
```

```yaml
# AppBundle/Resources/config/services.yml
services:
  faker.provider.markdownpost:
      class: AppBundle\DataFixtures\Faker\Provider\MarkdownPostProvider
      arguments: [ @hautelook_alice.faker ]
      tags: [ { name: hautelook_alice.faker.provider } ]
```

```php
<?php

// src/AppBundle/DataFixtures/Faker/Provider/MarkdownPostProvider.php

namespace AppBundle\DataFixtures\Faker\Provider;

class MarkdownPostProvider extends \Faker\Provider\Base
{
    const MAX_PARAGRAPHS = 10;

    public function markdownPost()
    {
        $paragraphs = $this->generator->paragraphs(self::MAX_PARAGRAPHS);

        // TODO : implements random markdown generation

        return $paragraphs;
    }
}
```
  
```bash
  [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]  
  Circular reference detected for service "faker.provider.markdownpost", path          
  : "hautelook_alice.doctrine.command.deprecated_load_command -> hautelook_al          
  ice.fixtures.loader -> hautelook_alice.alice.fixtures.loader -> hautelook_a          
  lice.faker.provider_chain -> faker.provider.markdownpost -> hautelook_alice          
  .faker".                                                                             
```

Did I misunderstand something?

### PR DESCRIPTION
**Pull request by theofidry**
Closes #129

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I think I still missing something.

From where the `hautelook_alice.bare_faker` service come from?

I tried:

```yaml
faker.provider.cron:
    class: CronExpressionGenerator\FakerProvider
    arguments: [ @hautelook_alice.bare_faker ]
    tags: [ { name: hautelook_alice.faker.provider } ]
```

And got:

```bash
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                  
  The service "faker.provider.cron" has a dependency on a non-existent service "hautelook_alice.bare_faker".  
```

**Comment by theofidry** [comment]
You have to declare it yourself cf. L55

**Comment by Soullivaneuh** [comment]
homer-doh

I should better read the doc twice. :+1:

**Comment by Soullivaneuh** [comment]
Hmm... now I have this:

```bash
  [InvalidArgumentException]   
  Unknown formatter "boolean"  
 ```

I just add your service from docs.

My cron fixture config:

```yml
AppBundle\Entity\Cron:
    cron (template):
        domain: @domain_*
        status: 1
        activated: <boolean(70)>
        comment: <sentence()>
        command: "php dummy.php >> /dev/null"
        # Use swekaj/cron-expression-generator when issue will be fixed: https://github.com/hautelook/AliceBundle/issues/129
#        frequency: '* * * * *'
        frequency: <cron()>
    cron_{0..200} (extends cron): ~
```

**Comment by theofidry** [comment]
Since it's a bare provider I guess you have to pass it `https://github.com/fzaninotto/Faker#fakerprovidermiscellaneous`, but it's kind of annoying...

**Comment by Soullivaneuh** [comment]
You mean another formatters are avoid with your method?

In this case, this is not a solution and the issue should be reopenned.

If the cron generator extends the base provider, it's especially because it's need other faker providers to work.

**Comment by theofidry** [comment]
Or actually we might rather use the `Faker\Factory::create()`method, not really sure.

Can you try:

```yaml
    hautelook_alice.bare_faker:
        class: Faker\Generator
        lazy: true
        factory: [ Faker\Factory, create ]
        arguments:
            - %hautelook_alice.locale%
        call:
            - method: seed
              arguments: [ %hautelook_alice.seed% ]
            - %hautelook_alice.seed%
```

?

**Comment by Soullivaneuh** [comment]
Works like a charm! \o/

I let you add this line on the doc. :+1:

**Pull request merged**
