### PR TITLE
Fix the append option

### PR DESCRIPTION
**Pull request by theofidry**
Depends on https://github.com/theofidry/AliceDataFixtures/pull/42

### CODE REVIEW

**Comment by theofidry** [comment]
Meh, other errors that I can't make sense of :/

**Comment by theofidry** [comment]
@WillGibson could you try out that PR to see if that works for you?

**Comment by WillGibson** [comment]
@theofidry I'm trying to test this PR in one of our projects, but I don't seem to be able to update the library...

```
        "hautelook/alice-bundle": "dev-theofidry:bugfix/fix-loader#latest",
        "nelmio/alice": "^3.0@rc",
        "theofidry/alice-data-fixtures": "^1.0.0@beta",
```

...leads to...

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package hautelook/alice-bundle dev-theofidry:bugfix/fix-loader#latest exists as hautelook/alice-bundle[0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.2, 1.x-dev, dev-master, 2.x-dev, v1.0.0, v1.0.0-beta, v1.0.0-beta.2, v1.0.0-beta.3, v1.0.0-beta.4, v1.0.0-beta.5, v1.1.0, v1.1.1, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.3.0, v1.3.1, v1.4.0, v1.4.1, v2.0.0-beta.0, v2.0.0-beta.1, v2.0.0-beta.2, v2.0.0-beta.3, dev-bugfix/fix-loader, dev-refactor/command-tests, dev-theofidry-patch-1] but these are rejected by your constraint.
```

Are you able to see what I'm doing wrong?

**Comment by theofidry** [comment]
```json
 "hautelook/alice-bundle": "dev-bugfix/fix-loader",
```

should do it with adding my repo as a VCS

**Comment by WillGibson** [comment]
Ah yes, silly me. Schoolboy error! Going to build one of our projects with it in our CI server now.

**Comment by WillGibson** [comment]
Oh, well, it made me update Symfony and twig too, which made other reasons for failing builds. I'll have another look in a bit.

**Comment by theofidry** [comment]
you can do a `composer update <package-name` to avoid that :)

**Comment by WillGibson** [comment]
I did, but I ended up with this in order to satisfy all the requirements...

```
composer update theofidry/alice-data-fixtures hautelook/alice-bundle nelmio/alice symfony/symfony twig/twig
```

**Pull request merged**
