### PR TITLE
Travis improvements

### PR DESCRIPTION
**Pull request by Soullivaneuh**
* PHP 7
* Multiple Symfony versions tests
* Lowest deps
* Composer file cache
* Composer dist install with github oauth
* Global phpunit install to avoid painful deps
* phpunit-bridge: https://packagist.org/packages/symfony/phpunit-bridge
* Symfony >= 2.3 minimum requirement (2.1 and 2.2 are deprecated).

To get it fully working, you need to set `GITHUB_OAUTH_TOKEN` on Travis.

For the token, no special authorization is needed, you can untick all. This is just for authentication.

Please remember to set `GITHUB_OAUTH_TOKEN` as a private variable so it will be not used on PR for security reasons.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@theofidry could you please cancel this job? https://travis-ci.org/hautelook/AliceBundle/builds/80807255

**Comment by Soullivaneuh** [comment]
@theofidry all green. :+1:

**Comment by theofidry** [comment]
Great, that's definitely better ;)

**Comment by Soullivaneuh** [comment]
@theofidry Did you rember to add `GITHUB_OAUTH_TOKEN` env?

**Comment by theofidry** [comment]
No, completely forgot :disappointed:

**Comment by Soullivaneuh** [comment]
Booh, go doing this important things! :-P

**Comment by theofidry** [comment]
In fact I not really sure of how to do that. I've created the token on GitHub and I've set the hash generated by travis in `.travis.yml`:

```yaml
env:
  global:
    - GITHUB_OAUTH_TOKEN="generated value"
```

Then what?

**Comment by Soullivaneuh** [comment]
Nope, you have to configure it on your Travis repository.

See: http://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

Please remember to ensure that display value is set to off. ;-)

**Comment by theofidry** [comment]
Done then

**Comment by Soullivaneuh** [comment]
:+1:

**Pull request merged**
