### PR TITLE
Maj composer to support doctrine bundle 2.x

### PR DESCRIPTION
**Pull request by cacahouwete**
https://github.com/hautelook/AliceBundle/issues/484

### CODE REVIEW

**Comment by juntereiner** [comment]
Why Travis failed here?

**Comment by theofidry** [comment]
Sorry somehow missed the PR. Restarting the build

**Comment by cacahouwete** [comment]
I don't understand why there are a "Segmentation fault" someone have an idea ?

**Comment by theofidry** [comment]
It's probably related to PHPDBG. I think it would be worth to do a separate PR to switch to pcov instead

**Comment by juntereiner** [comment]
> It's probably related to PHPDBG. I think it would be worth to do a separate PR to switch to pcov instead

Here we go: https://github.com/hautelook/AliceBundle/pull/488

**Comment by DanieleGBX** [comment]
With #488 merged, is there anything else blocking this PR?

**Comment by cacahouwete** [comment]
It's green ! Ready to be merged ;)

**Comment by juntereiner** [comment]
Could we merge this and make a new release from it, so it will be the last release compatible with SF 3.4/4.4 and still able to use doctrine bundle 2.x ? We cannot update to SF 4.4 until this get merged.

The other PR https://github.com/hautelook/AliceBundle/pull/487 could be used for SF5 compatiblity + clean up.

**Comment by cacahouwete** [comment]
@theofidry is it possible to merge it ? (I don't have write access)

**Comment by theofidry** [comment]
Done!

**Comment by beejaz** [comment]
@theofidry Hi, will this be released as a version v2.5.2? As I understand, its merged to master but not released yet? Are we waiting for other dependencys?

**Comment by theofidry** [comment]
I kinda hoped for #487 to be in, but if there is no new PR for the Symfony 5 support I'll tag a release at the end of the week

**Pull request merged**
